services:
  - type: web
    name: unichess
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 webapp:app
    plan: free
